on:
  push:
    tags:
      - 'v*'

name: Publish Release

jobs:
  build:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment variables
        uses: actions/github-script@v6
        with:
          script: |
            const ref = '${{ github.ref }}'

            const isPrerelease = /beta/.test(ref)

            core.exportVariable('IS_PRERELEASE', isPrerelease)
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Pack extension
        run: npm run pack
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ env.IS_PRERELEASE }}
          files: codimd-book.zip
